### ISSUE TITLE
"gulp light" and "gulp dark" throwing ENOENT

### ISSUE THREAD

**Issue by kmiklas** [barmalei/yuidoc-zebkit-theme#1] opened 2017-08-21 19:49 UTC
[27]: gulp light
[15:47:56] Using gulpfile ~\Keith\git\yuidoc-zebkit-theme\gulpfile.js
[15:47:56] Starting 'light-theme-cp'...
[15:47:56] Finished 'light-theme-cp' after 116 ms
[15:47:56] Starting 'light-theme-rn'...
[15:47:56] Finished 'light-theme-rn' after 13 ms
[15:47:56] Starting 'light'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn yuidoc ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by barmalei** [comment] 2017-08-21 19:54
Is yuidoc installed on your system ?

**Comment by kmiklas** [comment] 2017-08-22 13:09
Thx for response; yes, yuidoc is installed.

The theme is working; I was able to apply the template to my docs with the following command:
`yuidoc -c yuidoc.json -t C:\Users\KMiklas\Keith\git\yuidoc-zebkit-theme\themes\dark .`

The generation of example docs is throwing.

**Comment by smaudet** [comment] 2017-10-01 02:24
Yeah, this repo is broken on Windows. Your spawn call in your gulpfile is unsafe.

IMO this was a really fucking stupid design decision - lets make the documentation for our platform depend on a third party tool which has bad support on a major platform...oh and lets not even document our dependencies.

*slow clap*.

Stop using broken shit?

I can confirm this works on linux....only after installing the undocumented global yuidoc dependency. I have not yet tried it from within nvm, but I suspect it might crash and burn spectacularly. Addl...as noted on the website, seems to be incomplete doco...

**Comment by smaudet** [comment] 2017-10-01 02:46
*Update*

If you want actual up-to-date documentation, ignore the incorrect information on the website, clone the main repo run the following (from inside your cloned directory):

```bash
npm i -g yuidocjs
npm install
gulp
```

Look in apidoc/dark, open index.html

**Comment by barmalei** [comment] 2017-10-01 08:00
So, the problem in your case is absence globally installed yuidoc ?

**Comment by kmiklas** [comment] 2017-10-01 17:24
@smaudet, be thankful that he took the time to create these docs. Yuidoc is not that bad.

**Comment by barmalei** [comment] 2017-10-16 08:10
Fixed with switching to cross-spawn.

**Closed as completed by barmalei** 2017-10-16 08:10 UTC
